dist: xenial

language: python

python:
  - "3.6"

branches:
  only:
    - hugo

before_install:
  - export TZ=Asia/Kolkata

install:
  - sudo python3 hugo.py

script:
  - hugo

deploy:
  - provider: firebase
    token: $FIREBASE_TOKEN
    skip_cleanup: true
    on:
      branch: hugo
  - provider: pages
    token: $GITHUB_TOKEN
    local_dir: public
    target_branch: master
    skip_cleanup: true
    on:
      branch: hugo