dist: xenial

language: python

python:
  - "3.6"

addons:
  snaps:
    - hugo

branches:
  only:
    - hugo

before_script:
  - export TZ=Asia/Kolkata
    - rm -rf public 2> /dev/null

script:
  - hugo

deploy:
  - provider: firebase
    token: $FIREBASE_TOKEN
    skip_cleanup: true
    on:
      branch: hugo
  - provider: pages
    github_token: $GITHUB_TOKEN
    local_dir: public
    target_branch: master
    skip_cleanup: true
    on:
      branch: hugo