branches:
  only:
    - hugo

before_install:
  - export TZ=Asia/Kolkata
  - sudo apt-get update

install:
  - sudo apt-get install hugo

script:
  - hugo

deploy:
  - provider: firebase
    token: $FIREBASE_TOKEN
    skip_cleanup: true
    on:
      branch: hugo
  - provider: pages
    token: $GITHUB_TOKEN
    local_dir: public
    target_branch: master
    skip_cleanup: true
    on:
      branch: hugo