baseurl = "/"
languageCode = "en-us"
theme = "hello-friend-ng"
  themeColor = "#00ffa2"

title = "Sayak B"
subtitle = ""
keywords = ""
copyright = "Sayak B"
readOtherPosts = "Read other posts"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "02-01-2006"
  dateformNumTime = "02-01-2006 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Sayak B | Jack of All Trades"
  keywords = "homepage, blog, sayak, sayak b, hacking, programming, music, edm, dj, producer"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"

  [params.logo]
    logoText = "$ cd /home/sayak-b"
    logoHomeLink = "/"

  # Social icons
  [[params.social]]
    name = "instagram"
    url  = "https://soundcloud.com/sayak-b"

  [[params.social]]
    name = "email"
    url  = "mailto:me@sayakb.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/sayak-brm"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/"

# And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "/posts"