baseurl = "/"
languageCode = "en-us"
theme = "hello-friend-ng"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "02-01-2006"
  dateformNumTime = "02-01-2006 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Sayak B | Jack of All Trades"
  keywords = "homepage, blog, sayak, sayak b, hacking, programming, music, edm, dj, producer"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"

[languages]
  [languages.en]
    title = "Sayak B"
    subtitle = "Jack of All Trades"
    keywords = ""
    copyright = "Sayak B"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "$ cd /home/sayak-b"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

	# You can create a language based menu
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts"

# And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "/posts"