---
new_page_extension: md
auto_deploy: true
admin_path: static/admin
webhook_url: 
sections:
- type: document
  path: content/about.md
  label: About
- type: directory
  path: content/projects
  label: Projects
  create: all
  match: "**/*"
  templates:
  - projects
- type: directory
  path: content/music
  label: Music
  create: all
  match: "**/*"
  new_doc_ext: '20190602103723'
- type: directory
  path: content/posts
  label: Posts
  create: all
  match: "**/*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
  publish_command: hugo -d public
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.55.2
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.55.2
  preview_output_directory: public
  output_directory: public
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
version: 0.55.2
