name: Build Hugo

on:
  push:
    branches: [ hugo ]
  pull_request:
    branches: [ hugo ]
  repository_dispatch:
    types: [update-event]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        ref: 'hugo'
        submodules: 'recursive'
        
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Patch Footer
      run: patch themes/hello-friend-ng/layouts/partials/footer.html -i footer.diff

    - name: Python Preprocessing
      run: python3 pre/main.py ${{ secrets.GH_USERNAME }} ${{ secrets.GH_TOKEN }}

    # Runs a single command using the runners shell
    - name: Build Hugo
      uses: lowply/build-hugo@v0.74.1

    # Include README.md
    - name: Include README
      run: cp README.md public/README.md

    # Deploy to Firebase
    - name: Firebase CLI Deployment
      uses: doonstore/firebase-deploy@v1
      with:
        params: --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        FIREBASE_PROJECT: ${{ secrets.FIREBASE_PROJECT }}
    
    # Deploy to GitHub Pages
    - name: GitHub Branch Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GH_TOKEN }}
        publish_branch: master
        publish_dir: public
